LampShade/ServicesHost/Areas/Administration/Pages/Comments/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CommentManagement.Application.Contract.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServicesHost.Areas.Administration.Pages.Comments
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public CommentSearchModel SearchModel;
        public List<CommentViewModel> modelview { get; set; }

        private readonly ICommentApplication commentApplication;

        public IndexModel(ICommentApplication commentApplication)
        {
            this.commentApplication = commentApplication;
        }

        public void OnGet(CommentSearchModel model)
        {
            modelview = commentApplication.Search(model);
        }

        public IActionResult OnGetCancel(long Id)
        {
            var result = commentApplication.Cancel(Id);
            if (result.IsSucsseded)
            {
                return RedirectToPage("./Index");
            }
            Message = result.Message;
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetConfirm(long Id)
        {
            var result = commentApplication.Confirm(Id);
            if (result.IsSucsseded)
            {
                return RedirectToPage("./Index");
            }
            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Comments/Index.cshtml
@page
@model Areas.Administration.Pages.Comments.IndexModel
@{
    ViewData["title"] = "مدیریت کامنت ها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در محصولات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام"/>
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Email"></label>
                        <input class="form-control" asp-for="SearchModel.Email" placeholder="ایمیل"/>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کامنت ها  (@Model.modelview.Count)</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>نام</th>
                                    <th>ایمیل</th>
                                    <th>پیام</th>
                                    <th>تاریخ تولید</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach (var i in Model.modelview)
                            {
                                <tr>
                                    <td>@i.Id</td>
                                    <td>@i.Name</td>
                                    <td>@i.Email</td>
                                    <td>@i.Message</td>
                                    <td>@i.CommentDate</td>
                                    <td class="text-center">
                                        @if (i.IsCanceled)
                                        {
                                            <span class="text-danger">کنسل شده</span>
                                        }
                                        @if(!i.IsCanceled&&!i.IsConfirmed)
                                        {
                                            <span class="text-warning">در انتظار</span>
                                        }
                                        @if (!i.IsCanceled && i.IsConfirmed)
                                        {
                                            <span class="text-success">تایید شده</span>
                                        }
                                    </td>
                                    <td>
                                        <a class="btn btn-danger btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Cancel" asp-route-Id="@i.Id">
                                            کنسل
                                                </a>
                                        @if (!i.IsConfirmed)
                                        {
                                                <a class="btn btn-success btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Confirm" asp-route-Id="@i.Id">
                                                    تایید
                                                </a>
                                        }

                                    </td>
                                </tr>
                            }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}