LampShade/ServicesHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace ServicesHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole command { get; set; }
        private readonly IRoleApplication roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            this.roleApplication = roleApplication;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPost(CreateRole command)
        {
            var result = roleApplication.Create(command);
            return new RedirectToPageResult("Index",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using _0_Framwork.Infrastructure;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace ServicesHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public List<SelectListItem> Permissions=new List<SelectListItem>();
        public EditRole command { get; set; }
        private readonly IRoleApplication roleApplication;
        private readonly IEnumerable<IPermissionExposer> exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            this.roleApplication = roleApplication;
            this.exposers = exposers;
        }

        public void OnGet(long id)
        {
            command = roleApplication.GetDetails(id);
            var permission = new List<PermissionDto>();
            foreach (var e in exposers)
            {
                var expos = e.Exposer();
                foreach (var (Key,value) in expos)
                {
                    permission.AddRange(value);
                    var group = new SelectListGroup()
                    {
                        Name=Key
                    };
                    foreach(var permissiond in value)
                    {
                        var ithem = new SelectListItem(permissiond.Name, permissiond.Code.ToString())
                        {
                            Group=group
                        };
                        if (command.MappedPermissions.Any(s => s.Code == permissiond.Code))
                            ithem.Selected = true;

                        Permissions.Add(ithem);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole Command)
        {
            var result= roleApplication.Edit(Command);
            return new RedirectToPageResult("Index",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServicesHost.Areas.Administration.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        public SelectList Categories;
        public CreateArticle command;
        private readonly IArticleCategoryApplication articleCategoryApplication;
        private readonly IArticleApplication articleApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication, IArticleApplication articleApplication)
        {
            this.articleCategoryApplication = articleCategoryApplication;
            this.articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Categories = new SelectList(articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }
        public IActionResult OnPost(CreateArticle command)
        {
            var result = articleApplication.Create(command);
            return RedirectToPage("./Index",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServicesHost.Areas.Administration.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        public EditArticle command;
        public SelectList Category;

        private readonly IArticleApplication articleApplication;
        private readonly IArticleCategoryApplication articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            this.articleApplication = articleApplication;
            this.articleCategoryApplication = articleCategoryApplication;
        }

        
        public void OnGet(long Id)
        {
            Category = new SelectList(articleCategoryApplication.GetArticleCategories(), "Id", "Name");
            command=articleApplication.GetDetails(Id);
        }
        public IActionResult OnPost(EditArticle command)
        {
            var result = articleApplication.Edit(command);
            return RedirectToPage("./Index", result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framwork.Infrastructure;
using DiscountManagement.Application.Contract.CustomerDiscount;
using InventoryManagement.Application.Contract.Inventory;
using InventoryManagement.Infrasturcture.Configuration.Permission;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Domain.ProductCategoryAgg;

namespace ServicesHost.Areas.Administration.Pages.Inventory
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public InventorySearchModel SearchModel;
        public List<InventoryViewModel> modelview;


        public SelectList Product;

        private readonly IProductApplication productApplication;
        private readonly IInventoryApplication inventoryApplication;

        public IndexModel(IProductApplication productApplication, IInventoryApplication inventoryApplication)
        {
            this.productApplication = productApplication;
            this.inventoryApplication = inventoryApplication;
        }
        [NeedsPermission(InventoryPermission.ListInventory)]
        public void OnGet(InventorySearchModel searchModel)
        {
            Product = new SelectList(productApplication.GetProducts(), "Id", "Name");
            modelview = inventoryApplication.Search(searchModel);
        }
        [NeedsPermission(InventoryPermission.CreateInventory)]

        public IActionResult OnGetCreate()
        {
            var command = new CreateInventory()
            {
                Products = productApplication.GetProducts()
            };
            return Partial("./Create", command );
        }
        [NeedsPermission(InventoryPermission.CreateInventory)]

        public IActionResult OnPostCreate(CreateInventory command)
        {
            var result = inventoryApplication.Create(command);
            return new JsonResult(result);
        }
        [NeedsPermission(InventoryPermission.EditInventory)]

        public IActionResult OnGetEdit(long id)
        {
            var inventory = inventoryApplication.GetDetails(id);
            inventory.Products = productApplication.GetProducts();
            return Partial("Edit", inventory);
        }
        [NeedsPermission(InventoryPermission.EditInventory)]

        public IActionResult OnPostEdit(EditInventory Command)
        {
            var resuly = inventoryApplication.Edit(Command);
            return new JsonResult(resuly);
        }
        [NeedsPermission(InventoryPermission.IncreaseInventory)]

        public IActionResult OnGetIncrease(long Id)
        {
            var result = new IncreaseInventory()
            {
                InventoryId = Id
            };
            return Partial("Increase",result);
        }
        [NeedsPermission(InventoryPermission.IncreaseInventory)]

        public IActionResult OnPostIncrease(IncreaseInventory command)
        {
            var result=inventoryApplication.Increase(command);
            if (result.IsSucsseded)
            {
                return new JsonResult(result);
                
            }
            Message = "عملیات ناموفق";
            return RedirectToPage("/Index");
        }
        [NeedsPermission(InventoryPermission.ReduceInventory)]

        public IActionResult OnGetReduce(long Id)
        {
            var result = new RecreaseInventory()
            {
                InventoryId = Id
            };
            return Partial("Reduce", result);
        }
        [NeedsPermission(InventoryPermission.ReduceInventory)]

        public IActionResult OnPostReduce(RecreaseInventory command)
        {
            var result = inventoryApplication.Reduce(command);
            if (result.IsSucsseded)
            {
                return new JsonResult(result);

            }
            Message = "عملیات ناموفق";
            return RedirectToPage("/Index");
        }
        [NeedsPermission(InventoryPermission.OprationLogInventory)]

        public IActionResult OnGetLog(long Id)
        {
            var result=inventoryApplication.GetOprationLog(Id);
            return Partial("OprationLog",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/Create.cshtml
@model InventoryManagement.Application.Contract.Inventory.CreateInventory
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد انبار جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصولات</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")'>
                        <option value="0">محصولات</option>
                    </select>
                    @*<span asp-validation-for="ProductId" class="error"></span>*@
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label">قیمت محصول</label>
                    <input type="text" class="form-control" asp-for="UnitPrice"/>
                    <span asp-validation-for="UnitPrice" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/Edit.cshtml
@model InventoryManagement.Application.Contract.Inventory.EditInventory
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title"> ویرایشس تخفیف </h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
<div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصولات</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")'>
                        <option value="0">انتخاب محصولات</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label">قیمت محصول</label>
                    <input type="text" class="form-control" asp-for="UnitPrice">
                    <span asp-validation-for="UnitPrice" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" asp-for="Id" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/Increase.cshtml
@model InventoryManagement.Application.Contract.Inventory.IncreaseInventory
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزایش موجودی انبار</h4>
</div>

<form asp-page="./Index" asp-page-handler="Increase"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد</label>
                    <input asp-for="Count" class="form-control" />
                    <span asp-validation-for="Count" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Discription" class="control-label">توضیحات</label>
                    <textarea rows="3" type="text" class="form-control" asp-for="Discription"></textarea>
                    <span asp-validation-for="Discription" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" asp-for="InventoryId" value="@Model.InventoryId" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/Index.cshtml
@page
@using InventoryManagement.Infrasturcture.Configuration.Permission
@model Areas.Administration.Pages.Inventory.IndexModel
@{
    ViewData["title"] = "مدیریت انبار";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a Permission="InventoryPermission.CreateInventory" class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد انبار جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در انبار</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">              
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                       <select asp-for="SearchModel.ProductId" asp-items="Model.Product" class="form-control">
                           <option value="0">گروه محصولی</option>
                       </select>
                    </div>
                    <div class="form-group m-r-10">
                        <div class="checkbox checkbox-primary">
                            <input asp-for="SearchModel.IsStock" />
                            <label asp-for="SearchModel.IsStock">جست و جو در ناموجود ها</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست انبار (@Model.modelview.Count)</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>محصول</th>
                                    <th>قیمت</th>
                                    <th>موجودی انبار</th>
                                    <th>تاریخ ایجاد</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                            @{ int j = 0;}
                            @foreach (var i in Model.modelview)
                            {
                                <tr>
                                    <td>@(++j)</td>
                                    <td>@i.Product</td>
                                    <td>@i.UnitPrice</td>
                                    <td>@i.CurrentCount</td>
                                    <td>@i.CreationDate</td>
                                    <td>
                                            <a Permission="InventoryPermission.EditInventory" class="btn btn-warning btn-custom waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./Index", "Edit",new {id=i.Id})">
                                            <i class="fa fa-edit"></i> ویرایش 
                                            </a>
                                            <a Permission="InventoryPermission.IncreaseInventory" class="btn btn-success waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./Index", "Increase",new {id=i.Id})">
                                            <i class="fa fa-plus"></i> افزایش موجودی
                                            </a>
                                            <a Permission="InventoryPermission.ReduceInventory" class="btn btn-danger waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./Index", "Reduce",new {id=i.Id})">
                                            <i class="fa fa-minus"></i> کاهش موجودی
                                            </a>
                                            <a Permission="InventoryPermission.OprationLogInventory" class="btn btn-primary waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./Index", "Log",new {id=i.Id})" onclick="$('.modal-dialog').css('width','60%')">
                                            <i class="fa fa-recycle"></i> مشاهده گردش انبار
                                            </a>
                                        </td>
                                </tr>
                            }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/OprationLog.cshtml
@model List<InventoryManagement.Application.Contract.Inventory.InventoryOprationViewModel>
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">سوابق گردش انبار</h4>
</div>

    <div class="modal-body">
        <table id="datatable" class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>تعداد</th>
                    <th>تاریخ</th>
                    <th>عملیات</th>
                    <th>موجودی فعلی</th>
                    <th>عملگر</th>
                    <th>توضیحات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model)
                {
                    <tr class="text-white @(i.Operation?"bg-success":"bg-danger")">
                        <td>@i.Id</td>
                        <td>@i.Count</td>
                        <td>@i.OprationDate</td>
                        <td>
                            @if (i.Operation)
                            {
                                <span>افزایش</span>
                            }
                            else
                            {
                                <span>کاهش</span>
                            }
                        </td>
                        <td>@i.CurrentCount</td>
                        <td>@i.Operator</td>
                        <td>@i.Description</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
    </div>

LampShade/ServicesHost/Areas/Administration/Pages/Inventory/Reduce.cshtml
@model InventoryManagement.Application.Contract.Inventory.RecreaseInventory
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">کاهش موجودی انبار </h4>
</div>

<form asp-page="./Index" asp-page-handler="Reduce"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد</label>
                    <input asp-for="Count" class="form-control" />
                    <span asp-validation-for="Count" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea rows="3" type="text" class="form-control" asp-for="Description"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" asp-for="InventoryId" value="@Model.InventoryId" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">کاهش</button>
    </div>
</form>