LampShade/ServicesHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace ServicesHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole command { get; set; }
        private readonly IRoleApplication roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            this.roleApplication = roleApplication;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPost(CreateRole command)
        {
            var result = roleApplication.Create(command);
            return new RedirectToPageResult("Index",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using _0_Framwork.Infrastructure;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace ServicesHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public List<SelectListItem> Permissions=new List<SelectListItem>();
        public EditRole command { get; set; }
        private readonly IRoleApplication roleApplication;
        private readonly IEnumerable<IPermissionExposer> exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            this.roleApplication = roleApplication;
            this.exposers = exposers;
        }

        public void OnGet(long id)
        {
            command = roleApplication.GetDetails(id);
            var permission = new List<PermissionDto>();
            foreach (var e in exposers)
            {
                var expos = e.Exposer();
                foreach (var (Key,value) in expos)
                {
                    permission.AddRange(value);
                    var group = new SelectListGroup()
                    {
                        Name=Key
                    };
                    foreach(var permissiond in value)
                    {
                        var ithem = new SelectListItem(permissiond.Name, permissiond.Code.ToString())
                        {
                            Group=group
                        };
                        if (command.MappedPermissions.Any(s => s.Code == permissiond.Code))
                            ithem.Selected = true;

                        Permissions.Add(ithem);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole Command)
        {
            var result= roleApplication.Edit(Command);
            return new RedirectToPageResult("Index",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServicesHost.Areas.Administration.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        public SelectList Categories;
        public CreateArticle command;
        private readonly IArticleCategoryApplication articleCategoryApplication;
        private readonly IArticleApplication articleApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication, IArticleApplication articleApplication)
        {
            this.articleCategoryApplication = articleCategoryApplication;
            this.articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Categories = new SelectList(articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }
        public IActionResult OnPost(CreateArticle command)
        {
            var result = articleApplication.Create(command);
            return RedirectToPage("./Index",result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServicesHost.Areas.Administration.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        public EditArticle command;
        public SelectList Category;

        private readonly IArticleApplication articleApplication;
        private readonly IArticleCategoryApplication articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            this.articleApplication = articleApplication;
            this.articleCategoryApplication = articleCategoryApplication;
        }

        
        public void OnGet(long Id)
        {
            Category = new SelectList(articleCategoryApplication.GetArticleCategories(), "Id", "Name");
            command=articleApplication.GetDetails(Id);
        }
        public IActionResult OnPost(EditArticle command)
        {
            var result = articleApplication.Edit(command);
            return RedirectToPage("./Index", result);
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Discount/ColleagueDiscount/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Discount.Management.Domain.ColleagueDiscountAgg;
using DiscountManagement.Application.Contract.ColleagueDiscount;
using DiscountManagement.Application.Contract.CustomerDiscount;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Domain.ProductCategoryAgg;

namespace ServicesHost.Areas.Administration.Pages.Discount.ColleagueDiscount
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public ColleagueDiscountSearchModel SearchModel;
        public List<ColleagueDiscountViewModel> modelview { get;  set; }


        public SelectList Product;

        private readonly IProductApplication productApplication;
        private readonly IColleagueDiscountApplication colleagueDiscountApplication;

        public IndexModel(IProductApplication productApplication, IColleagueDiscountApplication colleagueDiscountApplication)
        {
            this.productApplication = productApplication;
            this.colleagueDiscountApplication = colleagueDiscountApplication;
        }

        public void OnGet(ColleagueDiscountSearchModel searchModel)
        {
            Product = new SelectList(productApplication.GetProducts(), "Id", "Name");
            modelview = colleagueDiscountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new DefineColleagueDiscount()
            {
                Products = productApplication.GetProducts()
            };
            return Partial("./Create", command );
        }

        public IActionResult OnPostCreate(DefineColleagueDiscount command)
        {
            var result = colleagueDiscountApplication.Define(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var customerdicount = colleagueDiscountApplication.GetDetails(id);
            customerdicount.Products = productApplication.GetProducts();
            return Partial("Edit", customerdicount);
        }

        public IActionResult OnPostEdit(EditColleagueDiscount Command)
        {
            var resuly = colleagueDiscountApplication.Edit(Command);
            return new JsonResult(resuly);
        }
        public IActionResult OnGetRemove(long Id)
        {
            var result = colleagueDiscountApplication.Remove(Id);
            if (result.IsSucsseded)
            {
                return RedirectToPage("./Index");
            }
            Message = result.Message;
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetRestore(long Id)
        {
            var result = colleagueDiscountApplication.Restore(Id);
            if (result.IsSucsseded)
            {
                return RedirectToPage("./Index");
            }
            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Discount/CustomerDiscount/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DiscountManagement.Application.Contract.CustomerDiscount;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Domain.ProductCategoryAgg;

namespace ServicesHost.Areas.Administration.Pages.Discount.CustomerDiscount
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public CustomerDiscountSearchModel SearchModel;
        public List<CustomerDiscountViewModel> modelview { get;  set; }


        public SelectList Product;

        private readonly IProductApplication productApplication;
        private readonly ICustomerDiscountApplication customerDiscountApplication;

        public IndexModel(IProductApplication productApplication, ICustomerDiscountApplication customerDiscountApplication)
        {
            this.productApplication = productApplication;
            this.customerDiscountApplication = customerDiscountApplication;
        }

        public void OnGet(CustomerDiscountSearchModel searchModel)
        {
            Product = new SelectList(productApplication.GetProducts(), "Id", "Name");
            modelview = customerDiscountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new DefineCustomerDiscount()
            {
                Products = productApplication.GetProducts()
            };
            return Partial("./Create", command );
        }

        public IActionResult OnPostCreate(DefineCustomerDiscount command)
        {
            var result = customerDiscountApplication.Define(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var customerdicount = customerDiscountApplication.GetDetails(id);
            customerdicount.Products = productApplication.GetProducts();
            return Partial("Edit", customerdicount);
        }

        public IActionResult OnPostEdit(EditCustomerDiscount Command)
        {
            var resuly = customerDiscountApplication.Edit(Command);
            return new JsonResult(resuly);
        }
        //public IActionResult OnGetNotIsStock(long Id)
        //{
        //    var result = productApplication.NotInStock(Id);
        //    if (result.IsSucsseded)
        //    {
        //        return RedirectToPage("./Index");
        //    }
        //    Message = result.Message;
        //    return RedirectToPage("./Index");
        //}
        //public IActionResult OnGetIsStock(long Id)
        //{
        //    var result = productApplication.InStock(Id);
        //    if (result.IsSucsseded)
        //    {
        //        return RedirectToPage("./Index");
        //    }
        //    Message = result.Message;
        //    return RedirectToPage("./Index");
        //}
    }
}

LampShade/ServicesHost/Areas/Administration/Pages/Discount/ColleagueDiscount/Create.cshtml
@model DiscountManagement.Application.Contract.ColleagueDiscount.DefineColleagueDiscount
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تعریف تخفیف همکاری جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصولات</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")'>
                        <option value="0">انتخاب محصولات</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DiscountRate" class="control-label">درصد تخفیف</label>
                    <input type="text" class="form-control" asp-for="DiscountRate">
                    <span asp-validation-for="DiscountRate" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade/ServicesHost/Areas/Administration/Pages/Discount/ColleagueDiscount/Edit.cshtml
@model DiscountManagement.Application.Contract.ColleagueDiscount.EditColleagueDiscount
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title"> ویرایشس تخفیف </h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
<div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصولات</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")'>
                        <option value="0">انتخاب محصولات</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DiscountRate" class="control-label">درصد تخفیف</label>
                    <input type="text" class="form-control" asp-for="DiscountRate">
                    <span asp-validation-for="DiscountRate" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade/ServicesHost/Areas/Administration/Pages/Discount/ColleagueDiscount/Index.cshtml
@page
@model Areas.Administration.Pages.Discount.ColleagueDiscount.IndexModel
@{
    ViewData["title"] = "مدیریت تخفیفات همکاران";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">تعریف تحفیف همکاران</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در تخفیفات همکاران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                       <select asp-for="SearchModel.ProductId" asp-items="Model.Product" class="form-control">
                           <option value="0">گروه محصولی</option>
                       </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست تخفیفات همکاران (@Model.modelview.Count)</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>محصول</th>
                                    <th>درصد تحفیف</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                            @{ int j = 0;}
                            @foreach (var i in Model.modelview)
                            {
                                <tr>
                                    <td>@(++j)</td>
                                    <td>@i.Product</td>
                                    <td>@i.DiscountRate</td>
                                    <td>@i.CreationDate</td>
                                    <td>
                                        <a class="btn btn-warning btn-custom waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./Index", "Edit",new {id=i.Id})">
                                            <i class="fa fa-edit"></i>
                                            </a>
                                        @if (!i.IsRemoved)
                                        {
                                            <a class="btn btn-danger btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Remove" asp-route-Id="@i.Id">
                                            غیر فعال
                                                </a>
                                        }else{
                                                    <a class="btn btn-success btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Restore" asp-route-Id="@i.Id">
                                           فعال
                                                </a>
                                       }
                                        </td>
                                </tr>
                            }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}